### ISSUE TITLE
IO Linc relay doesn't work

### ISSUE THREAD

**Issue by jfarre20** [teharris1/insteon2#14]
When trying to trigger an IOLinc relay, I get the following error:

`Failed to call service switch/turn_on. async_on() got an unexpected keyword argument 'group'`

My entity is switch.i_o_linc_45_34_d8_group_1
Previous insteon integration called this switch.i_o_linc_45_34_d8_relay and worked fine

Failing on line 29 in switch .py [await self._insteon_device.async_on(group=self._insteon_device_group.group)]

I suspect the _group_1 part is causing this.

**Comment by teharris1** [comment]
I did recently change the name of the relay back to relay (it was switch for some time). But I am confused why the `_group_1` would be appended to the name. That is odd. 

The error is not related to the entity name. It is related to how the `pyinsteon` module is receiving the on/off call. I just update `pyinsteon` to address this.

This may change the entity name back to `_relay`. If it does not please let me know because I don't want to create a breaking change for such as basic thing.

**Comment by teharris1** [comment]
I see why `_group_` was added. I have updated the `insteon2` code to fix that.

**Comment by jfarre20** [comment]
That fixed it
